### ISSUE TITLE
Only last calendar staying synced

### ISSUE THREAD

**Issue by staticnullnet** [NSueiro/MultipleCalendarSyncForGoogleHome#1]
I tried syncing two calendars. Only the last calendar in the list is getting synced. Upon removal of this line  

> old_events[i].deleteEvent();

both calendars did sync, but with the obvious side effect of duplicates as expected.

**Comment by NSueiro** [comment]
I think i know what’s going on. Let me run some tests and update the code. I’ll let you know as soon as it’s fixed. 

Thanks for the heads up!

**Comment by NSueiro** [comment]
Fixed! New version is already on master.

Please let mw know if it works for you!

**Comment by staticnullnet** [comment]
Working now!
